# Generated by Django 4.0.1 on 2022-02-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userfollow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollow',
            name='user_to_add',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
