# Generated by Django 4.0.1 on 2022-02-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_review_img_ticket_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='img',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
